name: docker

on:
    push:
    workflow_dispatch:

jobs:
    docker:
        runs-on: ubuntu-latest
        env:
            USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        steps:
            - name: login dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{ env.USERNAME }}
                password: ${{ env.PASSWORD }}
            - name: checkout code
              uses: actions/checkout@v4
            - name: build docker image
              run: docker build -t $USERNAME/exo3spring .
 
            - name: Get Project spring exercise 3
              run: docker push $USERNAME/exo3spring
