name: Issue creation alert
on:
    issues:
        types: opened

jobs:
    commentaire:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            - name: Answer to issue
              env:
                ISSUE_URL: ${{ github.event.issue.html_url}}
                AUTHOR_NAME: ${{ github.event.issue.user.login}}
                ISSUE_NAME: ${{ github.event.issue.title}}
              run: gh issue comment $ISSUE_URL --body "Bonjour $AUTHOR_NAME, nous avons pris en compte votre probleme du nom de :/ $ISSUE_NAME"


    

