# Nom pour le workflow
name: Build Spring App

# Declencher workflow lors du push d'application
on: 
    push:
        branches:
            - main
            
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Etape 1 : cherchez dans le marketplace l'action pour configurer le jdk
            - name: Set up jdk 17
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin' # See 'Supported distributions' for available options
                java-version: '17'

            # Etape 2 : Récupération du projet
            - name: Checkoutproject
              uses: actions/checkout@v4

            - name: Install dependencies
              run: mvn dependency:resolve

            - name: Build application
              run: mvn clean package



    

